# Generated by Django 3.2.7 on 2021-10-20 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HelpGuidancePost',
        ),
    ]
