# Generated by Django 3.2.7 on 2021-10-22 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0003_helpguidance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helpguidance',
            options={'verbose_name_plural': 'Help & Guidance'},
        ),
    ]
