# Generated by Django 3.2.9 on 2021-11-09 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0005_postcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostComment',
        ),
    ]
